services:
  - type: web
    name: n8n-server
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "n8n start"
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "123456"
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_TUNNEL_URL
        value: ""   # ← se completará cuando Render te genere la URL
